### ISSUE TITLE
Construct a logger

### ISSUE THREAD

**Issue by CodyNault** [OpenSuede/WebSocket-Stress-Test#8]
We need an application logger!

I don't think that we want to be passing logger references around so I think that it should operate entirely as statically accessible methods. It will likely need to have an initialize method and a finalize method that we can call manually e.g. SuedeLogger::finalize() would destroy the logger, de-allocate any memory it used and close any file handles. 

Since this application will be highly asynchronous, it is important that methods that modify files are entirely thread-safe. C++11 added a thread library where you can use std::mutex. This is sort of like using the synchronized keyword in java.

We need to differentiate between errors, warnings and debugging info in the logger. 

I would like to be able to have the logger print to standard err for debugging purposes.

Currently the Makefile sets up a ./log folder in the root of the project directory. Construct all log files in there.

**Comment by GarrettMorrison** [comment]
Since I can't self-assign I will go ahead and claim this one and you can assign me to it. I already have some basic logging code done so it shouldn't be too hard to modify it to work with these requirements (but we'll see).

**Comment by CodyNault** [comment]
Also, any good logger will record the system date/time with each event in the log file. Maybe not when it is printing to standard-error though, just to file.

**Comment by GarrettMorrison** [comment]
I think it should be safe to close this issue now as the logger now fulfils all the functions outlined here(also maybe we should move these issues over to the Suede section).

**Comment by CodyNault** [comment]
Thank you sir!
